"""add review mining foundation

Revision ID: 39f68cc4af54
Revises: aa11817b3ea4
Create Date: 2026-07-13 19:31:48.794175
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "39f68cc4af54"
down_revision: str | None = "aa11817b3ea4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_name", sa.String(length=200), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_platform", sa.String(length=100), nullable=False),
        sa.Column("import_method", sa.String(length=30), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=True),
        sa.Column("original_file_hash", sa.String(length=64), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("record_count_submitted", sa.Integer(), nullable=False),
        sa.Column("record_count_accepted", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("import_status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("metadata_snapshot", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_import_batches_import_status"),
        "review_import_batches",
        ["import_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_import_batches_is_fictional"),
        "review_import_batches",
        ["is_fictional"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_import_batches_original_file_hash"),
        "review_import_batches",
        ["original_file_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_import_batches_product_id"),
        "review_import_batches",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_import_batches_source_platform"),
        "review_import_batches",
        ["source_platform"],
        unique=False,
    )
    op.create_table(
        "review_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=False),
        sa.Column("external_review_id", sa.String(length=300), nullable=True),
        sa.Column("source_platform", sa.String(length=100), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("reviewer_display_name", sa.String(length=300), nullable=True),
        sa.Column("rating", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("rating_scale", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("review_title", sa.Text(), nullable=True),
        sa.Column("original_review_body", sa.Text(), nullable=False),
        sa.Column("normalized_review_text", sa.Text(), nullable=False),
        sa.Column("review_date", sa.Date(), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_purchase", sa.Boolean(), nullable=True),
        sa.Column("helpful_vote_count", sa.Integer(), nullable=True),
        sa.Column("geography", sa.String(length=150), nullable=True),
        sa.Column("language", sa.String(length=30), nullable=True),
        sa.Column("variant_sku", sa.String(length=300), nullable=True),
        sa.Column("provenance_type", sa.String(length=50), nullable=False),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("normalized_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("duplicate_status", sa.String(length=30), nullable=False),
        sa.Column("duplicate_of_review_id", sa.Integer(), nullable=True),
        sa.Column("active_classification_version", sa.Integer(), nullable=True),
        sa.Column("manually_flagged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["duplicate_of_review_id"],
            ["review_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["review_import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_records_duplicate_of_review_id"),
        "review_records",
        ["duplicate_of_review_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_records_duplicate_status"),
        "review_records",
        ["duplicate_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_records_external_review_id"),
        "review_records",
        ["external_review_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_records_import_batch_id"),
        "review_records",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_records_is_fictional"), "review_records", ["is_fictional"], unique=False
    )
    op.create_index(
        op.f("ix_review_records_manually_flagged"),
        "review_records",
        ["manually_flagged"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_records_normalized_fingerprint"),
        "review_records",
        ["normalized_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_records_product_id"), "review_records", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_records_review_date"), "review_records", ["review_date"], unique=False
    )
    op.create_index(
        op.f("ix_review_records_source_platform"),
        "review_records",
        ["source_platform"],
        unique=False,
    )
    op.create_table(
        "review_classification_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("classification_method", sa.String(length=50), nullable=False),
        sa.Column("classifier_version", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("reason_for_new_version", sa.Text(), nullable=False),
        sa.Column("supersedes_version_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["review_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["review_classification_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_id", "version_number"),
    )
    op.create_index(
        op.f("ix_review_classification_versions_is_active"),
        "review_classification_versions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_classification_versions_review_id"),
        "review_classification_versions",
        ["review_id"],
        unique=False,
    )
    op.create_table(
        "review_theme_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("classification_version_id", sa.Integer(), nullable=False),
        sa.Column("theme", sa.String(length=100), nullable=False),
        sa.Column("subtheme", sa.String(length=150), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("matching_evidence", sa.Text(), nullable=True),
        sa.Column("classification_source", sa.String(length=50), nullable=False),
        sa.Column("human_confirmed_status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["classification_version_id"],
            ["review_classification_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("classification_version_id", "theme", "subtheme"),
    )
    op.create_index(
        op.f("ix_review_theme_assignments_classification_version_id"),
        "review_theme_assignments",
        ["classification_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_theme_assignments_theme"),
        "review_theme_assignments",
        ["theme"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_theme_assignments_theme"), table_name="review_theme_assignments")
    op.drop_index(
        op.f("ix_review_theme_assignments_classification_version_id"),
        table_name="review_theme_assignments",
    )
    op.drop_table("review_theme_assignments")
    op.drop_index(
        op.f("ix_review_classification_versions_review_id"),
        table_name="review_classification_versions",
    )
    op.drop_index(
        op.f("ix_review_classification_versions_is_active"),
        table_name="review_classification_versions",
    )
    op.drop_table("review_classification_versions")
    op.drop_index(op.f("ix_review_records_source_platform"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_review_date"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_product_id"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_normalized_fingerprint"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_manually_flagged"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_is_fictional"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_import_batch_id"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_external_review_id"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_duplicate_status"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_duplicate_of_review_id"), table_name="review_records")
    op.drop_table("review_records")
    op.drop_index(
        op.f("ix_review_import_batches_source_platform"), table_name="review_import_batches"
    )
    op.drop_index(op.f("ix_review_import_batches_product_id"), table_name="review_import_batches")
    op.drop_index(
        op.f("ix_review_import_batches_original_file_hash"), table_name="review_import_batches"
    )
    op.drop_index(op.f("ix_review_import_batches_is_fictional"), table_name="review_import_batches")
    op.drop_index(
        op.f("ix_review_import_batches_import_status"), table_name="review_import_batches"
    )
    op.drop_table("review_import_batches")
    # ### end Alembic commands ###
