"""initial phase one schema

Revision ID: 91d4d22e6ae8
Revises:
Create Date: 2026-07-13 15:58:04.860921
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "91d4d22e6ae8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_log_entity_id"), "audit_log", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_log_entity_type"), "audit_log", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_log_event_type"), "audit_log", ["event_type"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("product_url", sa.String(length=1000), nullable=True),
        sa.Column("source_platform", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=150), nullable=True),
        sa.Column("target_customer", sa.Text(), nullable=True),
        sa.Column("customer_problem", sa.Text(), nullable=True),
        sa.Column("proposed_selling_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("product_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("packaging_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payment_processing_estimate", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expected_refund_allowance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estimated_cac", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("platform_cost_allocation", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("chargeback_allowance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_estimate", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("supplier", sa.String(length=200), nullable=True),
        sa.Column("supplier_location", sa.String(length=200), nullable=True),
        sa.Column("shipping_time", sa.String(length=100), nullable=True),
        sa.Column("minimum_order_quantity", sa.Integer(), nullable=True),
        sa.Column("marketplace_evidence", sa.Text(), nullable=True),
        sa.Column("search_evidence", sa.Text(), nullable=True),
        sa.Column("social_evidence", sa.Text(), nullable=True),
        sa.Column("competition_notes", sa.Text(), nullable=True),
        sa.Column("review_complaints", sa.Text(), nullable=True),
        sa.Column("upsell_ideas", sa.Text(), nullable=True),
        sa.Column("repeat_purchase_potential", sa.Text(), nullable=True),
        sa.Column("fulfillment_risk", sa.Text(), nullable=True),
        sa.Column("legal_policy_concerns", sa.Text(), nullable=True),
        sa.Column("research_notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_status"), "products", ["status"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("evidence_type", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("numeric_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit", sa.String(length=100), nullable=True),
        sa.Column("geography", sa.String(length=150), nullable=True),
        sa.Column("time_period", sa.String(length=150), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collection_method", sa.String(length=100), nullable=False),
        sa.Column("confidence_level", sa.String(length=20), nullable=False),
        sa.Column("provenance", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_collected_at"), "evidence", ["collected_at"], unique=False)
    op.create_index(op.f("ix_evidence_evidence_type"), "evidence", ["evidence_type"], unique=False)
    op.create_index(op.f("ix_evidence_product_id"), "evidence", ["product_id"], unique=False)
    op.create_table(
        "score_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("base_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("penalty_total", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("final_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.Column("penalties", sa.JSON(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_score_snapshots_final_score"), "score_snapshots", ["final_score"], unique=False
    )
    op.create_index(
        op.f("ix_score_snapshots_product_id"), "score_snapshots", ["product_id"], unique=False
    )
    op.create_table(
        "status_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("previous_status", sa.String(length=50), nullable=False),
        sa.Column("new_status", sa.String(length=50), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("supporting_evidence", sa.Text(), nullable=True),
        sa.Column("next_action", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_status_history_new_status"), "status_history", ["new_status"], unique=False
    )
    op.create_index(
        op.f("ix_status_history_product_id"), "status_history", ["product_id"], unique=False
    )
    op.create_table(
        "supplier_offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("minimum_order_quantity", sa.Integer(), nullable=True),
        sa.Column("evidence_quality", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_offers_product_id"), "supplier_offers", ["product_id"], unique=False
    )
    op.create_table(
        "validation_experiments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("test_type", sa.String(length=100), nullable=False),
        sa.Column("audience", sa.Text(), nullable=True),
        sa.Column("channel", sa.String(length=100), nullable=True),
        sa.Column("offer", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("creative", sa.Text(), nullable=True),
        sa.Column("budget_ceiling", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("visits", sa.Integer(), nullable=False),
        sa.Column("email_signups", sa.Integer(), nullable=False),
        sa.Column("add_to_carts", sa.Integer(), nullable=False),
        sa.Column("checkout_initiations", sa.Integer(), nullable=False),
        sa.Column("purchases", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("refunds", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("conversion_rate", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("customer_acquisition_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("contribution_profit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("lessons", sa.Text(), nullable=True),
        sa.Column("decision", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_validation_experiments_product_id"),
        "validation_experiments",
        ["product_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_validation_experiments_product_id"), table_name="validation_experiments")
    op.drop_table("validation_experiments")
    op.drop_index(op.f("ix_supplier_offers_product_id"), table_name="supplier_offers")
    op.drop_table("supplier_offers")
    op.drop_index(op.f("ix_status_history_product_id"), table_name="status_history")
    op.drop_index(op.f("ix_status_history_new_status"), table_name="status_history")
    op.drop_table("status_history")
    op.drop_index(op.f("ix_score_snapshots_product_id"), table_name="score_snapshots")
    op.drop_index(op.f("ix_score_snapshots_final_score"), table_name="score_snapshots")
    op.drop_table("score_snapshots")
    op.drop_index(op.f("ix_evidence_product_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_evidence_type"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_collected_at"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_products_status"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_audit_log_event_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_entity_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
