"""add product versions opportunities and research

Revision ID: aa11817b3ea4
Revises: 91d4d22e6ae8
Create Date: 2026-07-13 18:15:54.177448
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

revision: str = "aa11817b3ea4"
down_revision: str | None = "91d4d22e6ae8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("unusual_reason", sa.Text(), nullable=True),
        sa.Column("customer_problem", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("attachment_reference", sa.String(length=1000), nullable=True),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("market", sa.String(length=200), nullable=True),
        sa.Column("possible_category", sa.String(length=150), nullable=True),
        sa.Column("possible_customer", sa.Text(), nullable=True),
        sa.Column("initial_hypothesis", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("evidence_confidence", sa.String(length=20), nullable=False),
        sa.Column("submitted_by", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("follow_up_questions", sa.Text(), nullable=True),
        sa.Column("things_that_shouldnt_be_true", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_opportunities_status"), "opportunities", ["status"], unique=False)
    op.create_index(
        op.f("ix_opportunities_things_that_shouldnt_be_true"),
        "opportunities",
        ["things_that_shouldnt_be_true"],
        unique=False,
    )
    op.create_index(op.f("ix_opportunities_title"), "opportunities", ["title"], unique=False)
    op.create_table(
        "opportunity_product_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("linked_by", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "product_id"),
    )
    op.create_index(
        op.f("ix_opportunity_product_links_opportunity_id"),
        "opportunity_product_links",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_product_links_product_id"),
        "opportunity_product_links",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "product_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("based_on_version", sa.Integer(), nullable=True),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=300), nullable=True),
        sa.Column("supporting_evidence", sa.Text(), nullable=True),
        sa.Column("provenance", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "version_number"),
    )
    op.create_index(
        op.f("ix_product_versions_product_id"), "product_versions", ["product_id"], unique=False
    )
    op.create_table(
        "research_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("section_key", sa.String(length=100), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.String(length=30), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "section_key", "version_number"),
    )
    op.create_index(
        op.f("ix_research_entries_product_id"), "research_entries", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_entries_section_key"), "research_entries", ["section_key"], unique=False
    )
    op.create_table(
        "opportunity_evidence_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("linked_by", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "evidence_id"),
    )
    op.create_index(
        op.f("ix_opportunity_evidence_links_evidence_id"),
        "opportunity_evidence_links",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_evidence_links_opportunity_id"),
        "opportunity_evidence_links",
        ["opportunity_id"],
        unique=False,
    )
    op.create_table(
        "product_field_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_version_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("previous_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=300), nullable=True),
        sa.Column("supporting_evidence", sa.Text(), nullable=True),
        sa.Column("provenance", sa.String(length=30), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_version_id"],
            ["product_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_field_changes_field_name"),
        "product_field_changes",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_field_changes_product_version_id"),
        "product_field_changes",
        ["product_version_id"],
        unique=False,
    )
    op.add_column(
        "products",
        sa.Column("current_version", sa.Integer(), server_default="1", nullable=False),
    )
    product_rows = op.get_bind().execute(sa.text("SELECT * FROM products")).mappings()
    snapshot_fields = (
        "name",
        "product_url",
        "source_platform",
        "category",
        "target_customer",
        "customer_problem",
        "proposed_selling_price",
        "product_cost",
        "shipping_cost",
        "packaging_cost",
        "payment_processing_estimate",
        "expected_refund_allowance",
        "estimated_cac",
        "platform_cost_allocation",
        "chargeback_allowance",
        "discount_estimate",
        "supplier",
        "supplier_location",
        "shipping_time",
        "minimum_order_quantity",
        "marketplace_evidence",
        "search_evidence",
        "social_evidence",
        "competition_notes",
        "review_complaints",
        "upsell_ideas",
        "repeat_purchase_potential",
        "fulfillment_risk",
        "legal_policy_concerns",
        "research_notes",
        "is_fictional",
    )
    version_table = sa.table(
        "product_versions",
        sa.column("product_id", sa.Integer),
        sa.column("version_number", sa.Integer),
        sa.column("based_on_version", sa.Integer),
        sa.column("snapshot", sa.JSON),
        sa.column("actor", sa.String),
        sa.column("reason", sa.Text),
        sa.column("source", sa.String),
        sa.column("supporting_evidence", sa.Text),
        sa.column("provenance", sa.String),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    baselines = [
        {
            "product_id": row["id"],
            "version_number": 1,
            "based_on_version": None,
            "snapshot": {field: row[field] for field in snapshot_fields},
            "actor": "system",
            "reason": "Baseline captured by Work Order 002 migration",
            "source": None,
            "supporting_evidence": None,
            "provenance": "User-entered",
            "created_at": datetime.now(UTC),
        }
        for row in product_rows
    ]
    if baselines:
        op.bulk_insert(version_table, baselines)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "current_version")
    op.drop_index(
        op.f("ix_product_field_changes_product_version_id"), table_name="product_field_changes"
    )
    op.drop_index(op.f("ix_product_field_changes_field_name"), table_name="product_field_changes")
    op.drop_table("product_field_changes")
    op.drop_index(
        op.f("ix_opportunity_evidence_links_opportunity_id"),
        table_name="opportunity_evidence_links",
    )
    op.drop_index(
        op.f("ix_opportunity_evidence_links_evidence_id"), table_name="opportunity_evidence_links"
    )
    op.drop_table("opportunity_evidence_links")
    op.drop_index(op.f("ix_research_entries_section_key"), table_name="research_entries")
    op.drop_index(op.f("ix_research_entries_product_id"), table_name="research_entries")
    op.drop_table("research_entries")
    op.drop_index(op.f("ix_product_versions_product_id"), table_name="product_versions")
    op.drop_table("product_versions")
    op.drop_index(
        op.f("ix_opportunity_product_links_product_id"), table_name="opportunity_product_links"
    )
    op.drop_index(
        op.f("ix_opportunity_product_links_opportunity_id"), table_name="opportunity_product_links"
    )
    op.drop_table("opportunity_product_links")
    op.drop_index(op.f("ix_opportunities_title"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_things_that_shouldnt_be_true"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_status"), table_name="opportunities")
    op.drop_table("opportunities")
    # ### end Alembic commands ###
